'use client'
import Link from 'next/link'
import { Trash2, Minus, Plus } from 'lucide-react'
import { PageLayout, Breadcrumbs } from '@/components/page-layout'
import { useCart, cartProduct, isCustomBuild } from '@/components/cart-provider'
import { formatCurrency } from '@/data/products'

export default function CartPage() {
  const { items, update, remove, clear, subtotal } = useCart()
  return <PageLayout><Breadcrumbs items={[{ label: 'Cart' }]} /><section className="page-hero compact"><p className="eyebrow">PC Shack / Basket</p><h1>Your <em>Basket</em></h1></section>{!items.length ? <div className="empty-state"><h2>Your basket is empty</h2><p>Add a product or configure a custom PC to start.</p><Link className="button button-primary" href="/shop">Continue Shopping</Link></div> : <div className="cart-layout"><div className="cart-items">{items.map(item => isCustomBuild(item) ? <div className="cart-row custom-build-row" key={item.productId}><div><p className="eyebrow">Custom PC build</p><h2>{item.buildName}</h2><p>{item.components.map(c => `${c.category}: ${c.name}`).join(' · ')}</p><small>Estimate only — final compatibility and pricing confirmed by PC Shack.</small></div><strong>{formatCurrency(item.total)}</strong><button onClick={() => remove(item.productId)} aria-label="Remove custom build"><Trash2 size={17} /></button></div> : (() => { const p = cartProduct(item.productId); return p && <div className="cart-row" key={item.productId}><img src={p.image} alt="" /><div><h2>{p.name}</h2><p>{formatCurrency(p.price)} each</p></div><div className="quantity"><button onClick={() => update(item.productId, item.quantity - 1)} aria-label="Decrease quantity"><Minus size={15} /></button><b>{item.quantity}</b><button onClick={() => update(item.productId, item.quantity + 1)} aria-label="Increase quantity"><Plus size={15} /></button></div><strong>{formatCurrency(p.price * item.quantity)}</strong><button onClick={() => remove(item.productId)} aria-label="Remove item"><Trash2 size={17} /></button></div> })())}<button className="text-link" onClick={clear}>Clear basket</button></div><aside className="order-summary"><h2>Order Summary</h2><p>Subtotal <strong>{formatCurrency(subtotal)}</strong></p><p>Delivery <span>To be configured</span></p><p>VAT <span>Not configured</span></p><hr /><h3>Total <strong>{formatCurrency(subtotal)}</strong></h3><Link className="button button-primary" href="/checkout">Review & Checkout</Link></aside></div>}</PageLayout>
}
